# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3'

# Define services
services:

  # App Service
  app:
    # Configuration for building the docker image for the service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    container_name: broom_app
#    tty: true
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped
    depends_on:
      - db
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

  # Mysql Service
  db:
    image: mysql:5.7
    restart: always
#    command: --init-file /data/application/init.sql
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    container_name: broom_db
#    tty: true
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
#      - ./init.sql:/data/application/init.sql
      - my-db:/var/lib/mysql
    logging:
      driver: none
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

# Names our volume
volumes:
  my-db:
networks:
  backend:
